data:
  langs:
    - da
  test_data_root: /work/wsd
  train_data_root:
    en:
      - training_datasets/semcor_en/semcor_en.data.xml
  sense_inventory: bnoffsets
  outpath: pretrained_models
  test_names:
    da:
      - test-da
  dev_name:
    - en
    - dev-en

  max_segments_in_batch: 1000
  force_reload: True
  inventory_dir: /work/xl-wsd/inventories

model:
  device: cuda
  encoder_name: bert-base-multilingual-cased
  wsd_model_name: batchnorm_wsd_classifier
  layers_to_use:
    - -1
    - -2
    - -3
    - -4
  cache_instances: True
  finetune_embedder: False 

training:
  num_epochs: 50
  gradient_accumulation: 1
  patience: 3
  learning_rate: 2e-5
  validation_metric: -loss
  gradient_clipping: 1
  

wandb:
  metrics_to_report:
    - f1
    - loss
    - epoch
  soft_match: True

random_seed: 421 
